name: d4_selection
version: 0.1.1
description: Transform the DOM by selecting elements and joining to data.
repository: https://github.com/luizbarboza/d4_selection

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  extension_type_unions: ^1.0.10
  web: ^0.4.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0
